const data = {
    products:[
        {
            _id: '1',
            name: 'Samsung 85',
            category: 'TV',
            image: '/images/samsung85.jpg',
            price: 1899,
            brand: 'Samsung',
            rating: 4.5,
            numReviewers: 11,
            description: 'Samsung 68',
        },
        {
            _id: '2',
            name: 'Sony 85',
            category: 'TV',
            image: '/images/sony65.jpg',
            price: 1999,
            brand: 'Sony',
            rating: 4.5,
            numReviewers: 18,
            description: 'Sony 85',
        },
        {
            _id: '3',
            name: 'TCL 85',
            category: 'TV',
            image: '/images/tcl85.jpg',
            price: 1699,
            brand: 'TCL',
            rating: 5,
            numReviewers: 32,
            description: 'TCL 85',
        },
        {
            _id: '4',
            name: 'LG 65',
            category: 'TV',
            image: '/images/lg65.jpg',
            price: 995,
            brand: 'LG',
            rating: 4.5,
            numReviewers: 17,
            description: 'LG 65',
        },
        {
            _id: '5',
            name: 'Samsung 65',
            category: 'TV',
            image: '/images/samsung65.jpg',
            price: 899,
            brand: 'Samsung',
            rating: 4.5,
            numReviewers: 11,
            description: 'Samsung 65',
        },
        {
            _id: '6',
            name: 'Vizio 65',
            category: 'TV',
            image: '/images/vizio65.jpg',
            price: 799,
            brand: 'Vizio',
            rating: 4.5,
            numReviewers: 124,
            description: 'Vizio 65',
        },
        {
            _id: '7',
            name: 'Insignia 43',
            category: 'TV',
            image: '/images/insignia43.jpg',
            price: 399,
            brand: 'Insignia',
            rating: 4,
            numReviewers: 14,
            description: 'Insignia 43',
        },
        {
            _id: '8',
            name: 'Samsung 43',
            category: 'TV',
            image: '/images/samsung43.jpg',
            price: 599,
            brand: 'Samsung',
            rating: 4,
            numReviewers: 45,
            description: 'Samsung 43',
        },
        {
            _id: '9',
            name: 'Toshiba 43',
            category: 'TV',
            image: '/images/toshiba43.jpg',
            price: 499,
            brand: 'Samsung',
            rating: 4,
            numReviewers: 18,
            description: 'Toshiba 43',
        },
        
    ],
        

    
};